import { describe, expect, it } from 'vitest';
import { defineFilter } from '../src/filter_spec.js';
import {
  filterableFieldPaths,
  generateFilterClient,
  generateFilterClients,
  sortableFieldPaths,
} from '../src/generate_client.js';

const sampleSpec = defineFilter({
  filterable: ['age', 'name', 'status'],
  sortable: ['age', 'name'],
  searchable: ['name'],
  relations: {
    posts: { filterable: ['title', 'published'] },
  },
  defaultSort: [{ field: 'name', direction: 'asc' }],
  defaultSize: 25,
  maxSize: 100,
});

describe('computed fields in codegen', () => {
  it('surfaces computed aliases in both filterable and sortable field unions', () => {
    const spec = defineFilter({
      filterable: ['first', 'last'],
      computed: { fullName: "first || ' ' || last", postCount: () => '(SELECT 1)' },
    });
    expect(filterableFieldPaths(spec)).toEqual(['first', 'last', 'fullName', 'postCount']);
    expect(sortableFieldPaths(spec)).toEqual(['first', 'last', 'fullName', 'postCount']);
    const code = generateFilterClient(spec, { name: 'people' });
    expect(code).toContain('"fullName"');
    expect(code).toContain('"postCount"');
  });
});

describe('filterableFieldPaths / sortableFieldPaths', () => {
  it('enumerates base + relation-dotted filterable paths', () => {
    expect(filterableFieldPaths(sampleSpec)).toEqual([
      'age',
      'name',
      'status',
      'posts.title',
      'posts.published',
    ]);
  });

  it('sortable relation columns default to the relation filterable list', () => {
    expect(sortableFieldPaths(sampleSpec)).toEqual([
      'age',
      'name',
      'posts.title',
      'posts.published',
    ]);
  });

  it('caps relation paths at maxDepth (0 → base columns only)', () => {
    expect(filterableFieldPaths(sampleSpec, 0)).toEqual(['age', 'name', 'status']);
  });

  it('deep relations respect the hop cap', () => {
    const deep = defineFilter({
      filterable: ['id'],
      relations: {
        author: {
          filterable: ['name'],
          relations: { team: { filterable: ['slug'] } },
        },
      },
    });
    expect(filterableFieldPaths(deep)).toEqual(['id', 'author.name', 'author.team.slug']);
    expect(filterableFieldPaths(deep, 1)).toEqual(['id', 'author.name']);
  });

  it("a '*' base allow-list contributes no enumerable base columns", () => {
    const wildcard = defineFilter({
      filterable: '*',
      relations: { posts: { filterable: ['title'] } },
    });
    expect(filterableFieldPaths(wildcard)).toEqual(['posts.title']);
  });
});

describe('generateFilterClient', () => {
  it('emits a typed client with field union, type map, meta and factory', () => {
    const out = generateFilterClient(sampleSpec, {
      name: 'people',
      fieldTypes: {
        age: { kind: 'number' },
        name: { kind: 'string' },
        status: { kind: 'string', enumValues: ['A', 'B'] },
      },
    });

    // Banner + client import.
    expect(out).toContain('// Code generated by @adonis-agora/filter. DO NOT EDIT.');
    expect(out).toContain(
      "import { filterQueryTyped as _filterQueryTyped } from '@adonis-agora/filter-client';",
    );

    // Field-name allow-list union (the security boundary).
    expect(out).toContain(
      'export type PeopleFilterFields = "age" | "name" | "status" | "posts.title" | "posts.published";',
    );

    // Per-field type map (drives operator narrowing) — enum + kinds.
    expect(out).toContain('export interface PeopleFilterFieldTypes {');
    expect(out).toContain('  "age": number;');
    expect(out).toContain('  "name": string;');
    expect(out).toContain('  "status": "A" | "B";');

    // Runtime metadata: fields/sortable/searchable/relations/types + cursor params.
    expect(out).toContain('  fields: ["age", "name", "status", "posts.title", "posts.published"],');
    expect(out).toContain('  sortable: ["age", "name", "posts.title", "posts.published"],');
    expect(out).toContain('  searchable: ["name"],');
    expect(out).toContain('  relations: ["posts"],');
    expect(out).toContain('  types: { "age": "number", "name": "string", "status": "string" },');
    expect(out).toContain('  defaultSort: [{ field: "name", direction: "asc" }],');
    expect(out).toContain('  cursorKeyset: ["name"],');
    expect(out).toContain('  defaultSize: 25,');
    expect(out).toContain('  maxSize: 100,');

    // Typed factory, parameterised by both the fields union and the type map.
    expect(out).toContain('export function peopleFilterQuery() {');
    expect(out).toContain(
      '  return _filterQueryTyped<PeopleFilterFields, PeopleFilterFieldTypes>();',
    );
  });

  it('omits the type map when no field types are supplied (field-name-safe only)', () => {
    const out = generateFilterClient(sampleSpec, { name: 'people' });
    expect(out).not.toContain('interface PeopleFilterFieldTypes');
    expect(out).toContain('  types: {},');
    expect(out).toContain('  return _filterQueryTyped<PeopleFilterFields>();');
  });

  it('falls back to a permissive `string` union for a wildcard allow-list', () => {
    const wildcard = defineFilter({ filterable: '*' });
    const out = generateFilterClient(wildcard, { name: 'audit' });
    expect(out).toContain('export type AuditFilterFields = string;');
    expect(out).toContain('  fields: [],');
  });

  it('honours a custom client module and name casing', () => {
    const out = generateFilterClient(sampleSpec, {
      name: 'blog-post',
      clientModule: '@my/client',
    });
    expect(out).toContain("from '@my/client';");
    expect(out).toContain('export type BlogPostFilterFields =');
    expect(out).toContain('export function blogPostFilterQuery() {');
    expect(out).toContain('export const blogPostFilterMeta = {');
  });

  it('supports typeRef and nullable field types', () => {
    const out = generateFilterClient(sampleSpec, {
      name: 'people',
      fieldTypes: {
        age: { kind: 'number', nullable: true },
        status: { typeRef: 'Role' },
      },
    });
    expect(out).toContain('  "age": number | null;');
    expect(out).toContain('  "status": Role;');
  });

  it('caps relation depth via the maxDepth option', () => {
    const out = generateFilterClient(sampleSpec, { name: 'people', maxDepth: 0 });
    expect(out).toContain('export type PeopleFilterFields = "age" | "name" | "status";');
    expect(out).toContain('  relations: ["posts"],');
  });
});

describe('generateFilterClients (manifest expansion)', () => {
  it('expands a manifest into per-spec modules with snake_case file names', () => {
    const generated = generateFilterClients({
      people: { spec: sampleSpec, fieldTypes: { age: { kind: 'number' } } },
      blogPost: { spec: defineFilter({ filterable: ['title'] }) },
    });

    expect(generated.map((g) => g.name)).toEqual(['people', 'blogPost']);
    expect(generated.map((g) => g.filename)).toEqual([
      'people_filter_client.ts',
      'blog_post_filter_client.ts',
    ]);
    expect(generated[0]?.code).toContain('export function peopleFilterQuery() {');
    expect(generated[0]?.code).toContain('  "age": number;');
    expect(generated[1]?.code).toContain('export type BlogPostFilterFields = "title";');
  });
});
